title:            Mainframe
description:      A Mainframe blog, just collect mainframe info for myself
url:              http://mainframe.echoff.com
signoff:          Mu-An
disqus_shortname: muan
facebook_appid:   604714799556697
google_analytics: UA-21332781-7
links: 
  - name:         About
    url:          /about
  - name:         Catalog
    url:          /catalog
    external:     true
  - name:         Email
    url:          mailto:huhan3@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/huhan3
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
